// import 'tailwindcss/tailwind.css'; 
import Head from 'next/head'

import { getSession, signOut } from 'next-auth/react'
import { NextPageContext } from 'next'
import useCurrentUser from '@/hooks/useCurrentUser';

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}

export default function Home() {
  const { data: user } = useCurrentUser();

  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-2xl text-red-500'>Ongoing Next JS project</h1>
        <p className='text-white'>Logged in as : {user?.name}</p>
        <button className='h-10 w-20 mt-2 bg-white' onClick={() => signOut()}>Logout</button>
      </main>
    </>
  )
}
